[package]
name = "yj-molecule"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "A KFX library in Rust"
readme = "README.md"
keywords = ["kfx", "api"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
